## **MISSING VALUES PRACTICE**

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, 25, np.nan, 30, 35]
})

In [2]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [3]:
df

    Age
0  20.0
1  25.0
2  27.5
3  30.0
4  35.0

In [4]:
df = pd.DataFrame({
    "Age": [20, 25, np.nan, 30, 35]
})
df['Age'] = df['Age'].fillna(df['Age'].median())

In [5]:
df

    Age
0  20.0
1  25.0
2  27.5
3  30.0
4  35.0

In [6]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", np.nan, "Male", "Female"]
})

df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [7]:
df

   Gender
0    Male
1  Female
2  Female
3    Male
4  Female

In [8]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "BMI": [25.2, np.nan, 30.1, 27.5, np.nan]
})

In [9]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(strategy = 'mean')
df['BMI'] = imputer.fit_transform(df[['BMI']])

In [10]:
df

    BMI
0  25.2
1  27.6
2  30.1
3  27.5
4  27.6

In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "BMI": [25, np.nan, 30, 28, np.nan]
})

In [12]:
print("Original Data")
print(df)

print("\nAfter Row Deletion")
print(df.dropna())

print("\nAfter Mean Imputation") 
df['BMI'] = df['BMI'].fillna(df['BMI'].mean()) 
print(df)

Original Data
    BMI
0  25.0
1   NaN
2  30.0
3  28.0
4   NaN

After Row Deletion
    BMI
0  25.0
2  30.0
3  28.0

After Mean Imputation
         BMI
0  25.000000
1  27.666667
2  30.000000
3  28.000000
4  27.666667

## **ENCODING PRACTICE**

In [13]:
import pandas as pd

df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green"],
    "Education": ["High School", "Bachelor's", "Master's"],
    "Purchased": ["Yes", "No", "Yes"]
})

print(df)

   Color    Education Purchased
0    Red  High School       Yes
1   Blue   Bachelor's        No
2  Green     Master's       Yes

In [14]:
from sklearn.preprocessing import LabelEncoder 
encoder = LabelEncoder() 
df['Purchased'] = encoder.fit_transform(df['Purchased'])

In [15]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories = [["High School", "Bachelor's", "Master's"]])
df['Education'] = encoder.fit_transform(df[['Education']])

In [16]:
encoded_df = pd.get_dummies(df['Color'])

In [17]:
encoded_df.head()

    Blue  Green    Red
0  False  False   True
1   True  False  False
2  False   True  False

In [18]:
df = pd.concat([df, encoded_df] , axis = 1)

In [19]:
df = df.drop(columns = ['Color'])

In [20]:
df

   Education  Purchased   Blue  Green    Red
0        0.0          1  False  False   True
1        1.0          0   True  False  False
2        2.0          1  False   True  False